package org.kuali.ole.deliver.checkout

import org.kuali.ole.OLEConstants
import org.kuali.ole.deliver.bo.OleLoanDocument
import org.kuali.ole.deliver.bo.OlePatronDocument
import org.kuali.ole.deliver.util.OleItemRecordForCirc
import org.kuali.ole.deliver.drools.DroolsConstants
import org.kuali.ole.deliver.util.DroolsResponse
import org.kuali.ole.deliver.util.NoticeInfo

rule "OneWeekLoanRenewal"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument(Integer.valueOf(getNumberOfRenewals()) < 10)
$d : DroolsResponse()
$n: NoticeInfo()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FULL","PGR","TP","UG","CERDIP","INTUG","INTTP","LCT","RESAST","ACHOS","SPORA","SPORET","SPORS","INTPGR"))
$i: OleItemRecordForCirc (getItemType() in ("ONE_WEEK"),
getItemLocation() in ("MAIN","EGHAM","DAGENHAM"))

then
 $d.setRuleMatched(true);
 $l.setCirculationPolicyId("OneWeekLoanRenewal");
 $l.loanPeriod("7-D","7-D");
 $n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end

rule "OneWeekLoanRenewal1"
agenda-group "renewal validation"
activation-group "renewal validation"
when

$l: OleLoanDocument(Integer.valueOf(getNumberOfRenewals()) >= 10)
$n: NoticeInfo()
$d : DroolsResponse()
$p: OlePatronDocument(getBorrowerTypeCode() in ("FULL","PGR","TP","UG","CERDIP","INTUG","INTTP","LCT","RESAST","ACHOS","SPORA","SPORET","SPORS","INTPGR"))
$i: OleItemRecordForCirc (getItemType() in ("ONE_WEEK"),
getItemLocation() in ("MAIN","EGHAM","DAGENHAM"))

then
 $d.setRuleMatched(true);
 $l.setCirculationPolicyId("OneWeekLoanRenewal1");
 $d.addErrorMessage("Patron has more than allowed limit of renewals");
 $d.addErrorMessageCode("ErrorMessageFromRule");
 $d.addOverridePermissions(DroolsConstants.GENERAL_BLOCK_PERMISSION);
 $l.loanPeriod("7-D","7-D");
 $n.setNoticeType(DroolsConstants.REGULAR_LOANS_NOTICE_CONFIG);
 end
